// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqOUum72usk0pPhgLPD6Ox2K4TBI7nXkw',
    appId: '1:652749251858:android:f3c62954f539fe3bbeffcb',
    messagingSenderId: '652749251858',
    projectId: 'buku-kontak-4f0c2',
    storageBucket: 'buku-kontak-4f0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXa9hbCeVEpXt22NmKpvv_f3wLnSDs-Bk',
    appId: '1:652749251858:ios:ea3fa4b0f60e3518beffcb',
    messagingSenderId: '652749251858',
    projectId: 'buku-kontak-4f0c2',
    storageBucket: 'buku-kontak-4f0c2.firebasestorage.app',
    iosBundleId: 'com.example.materialDesign',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIs_es6ZX9-TTw59daFXsqJ0hPviUiCZc',
    appId: '1:652749251858:web:cd297b175e6c147ebeffcb',
    messagingSenderId: '652749251858',
    projectId: 'buku-kontak-4f0c2',
    authDomain: 'buku-kontak-4f0c2.firebaseapp.com',
    storageBucket: 'buku-kontak-4f0c2.firebasestorage.app',
  );

}